=== JesusMartinezCamps/lenguajeMarcas/ejer4ValidarXML_DTD/questions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT questions (question)+>
<!ELEMENT question (type,text,answer*,option*)>

<!ATTLIST question id ID #REQUIRED>

<!ELEMENT type (#PCDATA|radio|checkbox|text|select|multiple)*>
<!ELEMENT text (#PCDATA)>
<!ELEMENT answer (#PCDATA)>
<!ELEMENT option (#PCDATA)>

=== JesusMartinezCamps/lenguajeMarcas/ejer4ValidarXML_DTD/questions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE questions SYSTEM "questions.dtd">
<questions>
    <question id="p1">
        <type>text</type>
        <text>¿Como se llama el burro que acompaña siempre a Shrek?</text>
        <answer>Asno</answer>
        <answer>Ninguna de las anteriores</answer>
        <answer>Burrito</answer>
    </question>
    <question id='p2'>
        <type>text</type>
        <text>En la pelicula Regreso al Futuro, ¿qué objeto funcionaba como máquina del tiempo?</text>
        <answer>una lavadora</answer>
        <answer>una camioneta</answer>
        <answer>una tostadora</answer>
        <answer>un coche</answer>
    </question>
    <question id='p3'>
        <type>select</type>
        <text>¿Quién es el director de Piratas del Caribe:La maldicion del perla negra?</text>
        <answer>Ted Elliott</answer>
        <answer>Gore Verbinski</answer>
        <answer>Hans Zimmer</answer>
        <answer>Terry Rossi</answer>
    </question>
    <question id='p4'>
        <type>select</type>
        <text>Selecciona los nombres que no correspondan al nombre de la pequeña protagonista en El Laberinto del Fauno?</text>
        <answer>Ofelia</answer>
        <answer>Amalia</answer>
        <answer>Teresa</answer>
        <answer>Yolanda</answer>
    </question>
    <question id="p5">
        <type>select multiple</type>
        <text>¿Selecciona los años que no correspondan a la fecha de la primera entrega de Matrix?</text>
        <answer>2000</answer>
        <answer>2001</answer>
        <answer>999</answer>
        <answer>1998</answer>
    </question>
    <question id='p6'>
        <type>select multiple</type>
        <text>De los siguientes pecado capitales, ¿cuales aparecen en la película Seven?</text>
        <answer>gula</answer>
        <answer>infidelidad</answer>
        <answer>lujuria</answer>
        <answer>orgullo</answer>
        <answer>robo</answer>
        <answer>pereza</answer>
    </question>
    <question id='p7'>
        <type>checkbox</type>
        <text>En Harry Potter, ¿cómo se denomina el hechizo asesino?</text>
        <answer>Abada Kadabra</answer>
        <answer>Avada Kedavra</answer>
        <answer>Abra Kadabra</answer>
    </question>
    <question id='p8'>
        <type>checkbox</type>
        <text>¿De qué compañia es la película Las Cronicas de Narnia?</text>
        <answer>Walt Disney Pictures</answer>
        <answer>Warners Brothers</answer>
        <answer>Dreamworks</answer>
    </question>
    <question id='p9'>
        <type>radio</type>
        <text>¿Que personaje le firma el libro a Harrison Ford en la tercera parte de Indiana Jones?</text>
        <answer >hitler</answer>
        <answer >samuel L.Jackson,</answer>
        <answer >brad pitt</answer>
    </question>
    <question id='p10'>
        <type>radio</type>
        <text>Noche en el museo: ¿de qué trabajaba Larry Daley antes de su trabajo como guardia del museo?</text>
        <answer>contable</answer>
        <answer>estaba desempleado</answer>
        <answer>jefe editorial,</answer>
        <answer>limpia cristales</answer>
    </question>
</questions>
